// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetShopTable() {
  return window['go']['main']['App']['GetShopTable']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function WriteData(arg1) {
  return window['go']['main']['App']['WriteData'](arg1);
}
