// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetShopTable():Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;

export function WriteData(arg1:Array<any>):Promise<void>;
