// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddShopItem(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function GetMenuItems(arg1:number):Promise<Array<number>>;

export function GetShopItems(arg1:number,arg2:number,arg3:number):Promise<Array<main.ShopItem>>;

export function GetShopTable():Promise<Array<number>>;

export function GetSubMenus(arg1:number,arg2:number):Promise<Array<number>>;

export function MatchItemName(arg1:string):Promise<string>;

export function ReloadItemMap():Promise<void>;

export function SearchItem(arg1:string):Promise<Array<main.ItemInfo>>;
