// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMenuItems(arg1) {
  return window['go']['main']['App']['GetMenuItems'](arg1);
}

export function GetShopItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetShopItems'](arg1, arg2, arg3);
}

export function GetShopTable() {
  return window['go']['main']['App']['GetShopTable']();
}

export function GetSubMenus(arg1, arg2) {
  return window['go']['main']['App']['GetSubMenus'](arg1, arg2);
}

export function SearchItem(arg1) {
  return window['go']['main']['App']['SearchItem'](arg1);
}
